/**
 * SQL validation for Claude-generated queries.
 * Provides a secondary safety layer on top of the read-only Postgres role.
 *
 * The read-only DB role is the primary security guarantee — it physically
 * prevents destructive SQL at the database level. This module is the
 * secondary layer: it rejects bad queries early, provides user-friendly
 * error messages, and enforces a row limit to prevent expensive full-table scans.
 *
 * See /lib/validation/README.md for the full list of enforced rules.
 */

/** Maximum rows the agent is allowed to fetch in a single query. */
export const MAX_ROWS = 1000;

/** Timeout in milliseconds before a query is cancelled. */
export const QUERY_TIMEOUT_MS = 10_000;

/**
 * The result of running a SQL string through the validator.
 */
export interface ValidationResult {
  valid: boolean;
  /** Human-readable reason for rejection. Only set when valid === false. */
  reason?: string;
  /** The (possibly modified) SQL to execute. Only set when valid === true. */
  sanitizedSql?: string;
}

/**
 * SQL keywords that indicate a write or destructive operation.
 * These are blocked regardless of position in the statement.
 */
const BLOCKED_KEYWORDS: string[] = [
  "INSERT",
  "UPDATE",
  "DELETE",
  "DROP",
  "TRUNCATE",
  "ALTER",
  "CREATE",
  "REPLACE",
  "MERGE",
  "UPSERT",
  "GRANT",
  "REVOKE",
  "EXECUTE",
  "CALL",
  "DO",
  "COPY",
  "VACUUM",
  "ANALYZE",
  "REINDEX",
  "CLUSTER",
  "LOCK",
  "SET",
  "RESET",
  "COMMENT",
  "SECURITY",
  "OWNER",
  "RENAME",
];

/**
 * Validates that a Claude-generated SQL string is safe to execute.
 *
 * Rules enforced:
 * 1. Must be a SELECT statement (starts with SELECT after normalization)
 * 2. Must not contain any blocked write/destructive keywords
 * 3. Must not contain semicolons after the trailing one (no statement chaining)
 * 4. Row limit is injected if not already present
 *
 * @param sql - The raw SQL string generated by Claude
 * @returns A ValidationResult indicating whether the query is safe to run
 */
export function validateSQL(sql: string): ValidationResult {
  // Normalize whitespace and case for consistent keyword matching
  const trimmed = sql.trim();
  const normalized = trimmed.toUpperCase();

  // Rule 1: Must start with SELECT — reject everything else immediately
  // This is also enforced at the DB level, but we reject early here
  // so we can return a clear, user-facing error message
  if (!normalized.startsWith("SELECT")) {
    return {
      valid: false,
      reason: "Only SELECT statements are allowed.",
    };
  }

  // Rule 2: Reject any statement containing blocked keywords
  // Using word-boundary matching to avoid false positives (e.g. 'TRUNCATED' in a value)
  for (const keyword of BLOCKED_KEYWORDS) {
    // \b ensures we match the whole word, not a substring
    const pattern = new RegExp(`\\b${keyword}\\b`, "i");
    if (pattern.test(trimmed)) {
      return {
        valid: false,
        reason: `Statement contains a disallowed keyword: ${keyword}.`,
      };
    }
  }

  // Rule 3: No statement chaining via semicolons
  // Strip the optional trailing semicolon, then check for any remaining ones
  const withoutTrailingSemicolon = trimmed.replace(/;\s*$/, "");
  if (withoutTrailingSemicolon.includes(";")) {
    return {
      valid: false,
      reason: "Statement chaining via semicolons is not allowed.",
    };
  }

  // Rule 4: Inject LIMIT if one is not already present
  // This caps rows at MAX_ROWS to prevent expensive full-table scans
  const sanitizedSql = injectRowLimit(withoutTrailingSemicolon);

  return { valid: true, sanitizedSql };
}

/**
 * Injects a LIMIT clause into a SELECT statement if one is not already present.
 * If a LIMIT already exists and exceeds MAX_ROWS, it is clamped down.
 *
 * @param sql - A normalized SELECT statement without a trailing semicolon
 * @returns The SQL with a safe LIMIT applied
 */
function injectRowLimit(sql: string): string {
  const normalized = sql.toUpperCase();

  // Check if a LIMIT clause already exists
  const limitMatch = normalized.match(/\bLIMIT\s+(\d+)/);

  if (limitMatch) {
    const existingLimit = parseInt(limitMatch[1], 10);

    // Clamp down if the existing limit exceeds our maximum
    if (existingLimit > MAX_ROWS) {
      return sql.replace(/\bLIMIT\s+\d+/i, `LIMIT ${MAX_ROWS}`);
    }

    // Existing limit is within bounds — return as-is
    return sql;
  }

  // No LIMIT found — append one
  return `${sql}\nLIMIT ${MAX_ROWS}`;
}
